import streamlit as st

st.title("Random Forest Interpretation")

st.write("The model to predict Yelp Score based on a variety of features was built using a random forest algorithm. We thought it would be a good model to use considering the many features we had (120). Before creating the random forest, we calculated and added Yelp Score to our data. Yelp Score was calculated as a function of star rating and number of reviews using a Bayesian average. The formula was (stars * review count + (mean stars * 25th percentile of review counts)) / (review count + 25th percentile of review counts). We settled on this method of a Yelp Score because a restaurant’s star rating does not paint a complete picture. We wanted to ensure a restaurant with a 4.7 star rating and 1000 reviews would have a higher Yelp Score than a restaurant with a 5 star rating and only 1 review.")
st.write("For our random forest model, we used 1000 trees and decided to bootstrap our data to encourage diverse trees and reduce overfitting. To decide the maximum depth of each tree in the forest, we plotted mean squared error as maximum depth increased:")
st.image("streamlit/mse_v_treedepth.png")
st.write("We minimize MSE at a maximum depth of 17, which we use. Above that, there appears to be some overfitting.")
st.write("Using these parameters, we return a final mean squared error of about .177. We believe this is a good error value for our model, as this small squared error would not, on average, change the meaning of a restaurant’s Yelp Score.")
st.write("In making our model, we decided to not include the feature average hours open because we found that this feature was likely encoding for another feature: fast food restaurants. We noticed that two of the top negative correlations with Yelp Score were average hours open at a correlation of -0.33 and then fast food at a correlation of -0.24. This lead us to believe that being a fast food restaurant is what decreases your Yelp Score, and since fast food restaurants are often open for longer hours than normal restaurants, average hours acts as a confounding variable with being a fast food restaurant. We found that keeping all else the same in the model, decreasing the average hours open to 0 actually increased the Yelp Score. This does not make intuitive sense for a prospective business to follow, so we decided to omit this feature from our model. ")
st.write("After using our model to test out some example prospective businesses, we determined that certain features are more important than others in predicting business success (or Yelp Score). Using the baseline example of a restaurant that is open 5 days a week in zip code 19107, has free wifi, casual attire, and a $ price range (leaving all else blank), the initial yelp score is 3.79. Changing the zip code to 19103 lowers the score to 3.65, other zip codes have scores even lower or in the 3.70s. Generally, all else being equal, changing location affects the Yelp Score. This suggests that location is an important factor to consider in a business, possible reasons including the prevalence of competitors as well as neighborhood characteristics. In our model, zip code is mapped to median household income, and income likely affects how much disposable income customers in that area have to spend at restaurants. ")
st.write("Using the same baseline above, we noticed that some ambience characteristics affect Yelp score, with 'touristy' and 'romantic' raising yelp score, and 'divey' lowering it. Looking at restaurant categories, we see that 'Pizza' lowers the yelp score to 3.6, 'Fast Food' lowers the yelp score to 3.45. 'Cheesesteaks' also surprisingly lowers the yelp score to 3.51, but perhaps people in Philly are really particular about their cheesesteaks. However, this number varies by zip code, suggesting that people have different opinions on types of restaurants in different parts of the city. All of this suggests that the category of the restaurant is important in determining how well a business does in a certain area. Overall, people tend to rate some categories higher than others. It is important to note that we are using Yelp Score as a metric of business success because it provides some measure of customer satisfaction which is inherently important in business. We recognize however, that other things, such as profit, are important in business success too. Nonetheless, happy customers generally lead to more profits if people are willingly and wanting to return to a business. So while it seems like consumers are dissatisfied with fast food restaurants, that’s not to say an existing large chain like McDonalds won’t still profit in this area, but that perhaps it isn’t the best idea to add another fast food chain here when people prefer other restaurants more, like Coffee and Tea shops (with a yelp score of 3.76).")
st.write("Lastly, often in opening a business, investors and prospective owners are interested in knowing what the business landscape looks like in the area of interest. Thus, when a user selects a zip code and category, a map is populated with existing restaurants of this category. For example, it might not be a good idea to open another coffee shop if there are already three on that street.")
